### ISSUE TITLE
qustion about file path of sms files

### ISSUE THREAD

**Issue by gabegaster** [mdezube/sms-analysis#4]
Have you checked that this works across phone versions, Windows/Mac/Linux platforms, etc? Where do these numbers come from and what is the guarantee that they are correct?

It would be good to call this out in the Readme as a dependency, if it is one.

```
MESSAGE_DB = '3d0d7e5fb2ce288813306e4d4636395e047a3d28'
ADDRESS_DB = '31bb7ba8914766d4ba40d6dfb6113c8b614be442'
```

**Comment by mdezube** [comment]
Those files should work across versions/platforms.  There is one platform dependent piece that I call out here: https://github.com/mdezube/sms-analysis/blob/master/README.md#dependencies although perhaps I should call it out in code as well?

**Comment by mdezube** [comment]
Resolved this in a recent PR, confirmed it works on Windows.
